  
steps:
- name: python:3.7
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'requirements.txt'
- name: 'gcr.io/${PROJECT_ID}/pylint'
  args: ['main.py']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
tags: ['cloud-builders-community']
timeout: "1600s"
